/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kopakabana;

import static kopakabana.Baza.druzyny;
import static kopakabana.Baza.mecze_lina;
import static kopakabana.Baza.mecze_ognie;
import static kopakabana.Baza.mecze_siatkowka;
import static kopakabana.Baza.sedziowie;

/**
 *
 * @author tuptu
 */
public class MeczFrame extends javax.swing.JFrame {
    
    int x =1; //1-siatkówka 2-gonie 3-lina
    /**
     * Creates new form MeczFrame
     */
    public MeczFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        wybor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        sedzia = new javax.swing.JComboBox<>();
        s3 = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        pomocniczy1 = new javax.swing.JComboBox<>();
        pomocniczy2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        goscie2 = new javax.swing.JComboBox<>();
        gospodarze2 = new javax.swing.JComboBox<>();
        w_gospodarze = new javax.swing.JTextField();
        w_goscie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        stworz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Goście:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Gospodarze:");

        wybor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "siatkówka", "ognie", "lina" }));
        wybor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyborActionPerformed(evt);
            }
        });

        jLabel3.setText("Dyscyplina:");

        sedzia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sedziaMouseClicked(evt);
            }
        });
        sedzia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sedziaActionPerformed(evt);
            }
        });

        s3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        s3.setText("pomocniczy:");

        s1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        s1.setText("Sędzia:");

        s2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        s2.setText("pomocniczy:");

        pomocniczy1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pomocniczy1MouseClicked(evt);
            }
        });
        pomocniczy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pomocniczy1ActionPerformed(evt);
            }
        });

        pomocniczy2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pomocniczy2MouseClicked(evt);
            }
        });

        jButton1.setText("<-Wróć");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        goscie2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goscie2MouseClicked(evt);
            }
        });
        goscie2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goscie2ActionPerformed(evt);
            }
        });

        gospodarze2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gospodarze2MouseClicked(evt);
            }
        });
        gospodarze2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gospodarze2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText(":");

        stworz.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        stworz.setText("Stówrz mecz");
        stworz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stworzActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(wybor, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(s2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pomocniczy1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(s3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sedzia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(gospodarze2, 0, 183, Short.MAX_VALUE)
                                    .addComponent(pomocniczy2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(w_gospodarze))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(w_goscie)
                            .addComponent(goscie2, 0, 183, Short.MAX_VALUE))
                        .addGap(90, 90, 90)))
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stworz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(wybor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goscie2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gospodarze2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sedzia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s2)
                    .addComponent(pomocniczy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s3)
                    .addComponent(pomocniczy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(w_goscie)
                    .addComponent(w_gospodarze))
                .addGap(18, 18, 18)
                .addComponent(stworz, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wyborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyborActionPerformed
        // TODO add your handling code here:
        String wybrano = (String) wybor.getSelectedItem();
        if("siatkówka".equals(wybrano)) {x =1;
        //sedziowei pomoc
        pomocniczy2.setVisible(true);
        pomocniczy1.setVisible(true);
        s2.setVisible(true);
        s3.setVisible(true);
        }
        if("ognie".equals(wybrano)){ x =2;
        pomocniczy2.setVisible(false);
        pomocniczy1.setVisible(false);
        s2.setVisible(false);
        s3.setVisible(false);        
        }
        if("lina".equals(wybrano)){ x =3;
        pomocniczy2.setVisible(false);  
        pomocniczy1.setVisible(false);
        s2.setVisible(false);
        s3.setVisible(false);        
        }
    }//GEN-LAST:event_wyborActionPerformed

    private void sedziaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sedziaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_sedziaActionPerformed

    private void sedziaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sedziaMouseClicked
        // TODO add your handling code here:
        sedzia.removeAllItems();
        for(Sedzia s : sedziowie){
            sedzia.addItem(s.imie+" "+s.nazwisko);
        }
    }//GEN-LAST:event_sedziaMouseClicked

    private void pomocniczy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pomocniczy1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pomocniczy1ActionPerformed

    private void pomocniczy1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pomocniczy1MouseClicked
        // TODO add your handling code here:
                pomocniczy1.removeAllItems();
        for(Sedzia s : sedziowie){
            pomocniczy1.addItem(s.imie+" "+s.nazwisko);
        }
    }//GEN-LAST:event_pomocniczy1MouseClicked

    private void pomocniczy2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pomocniczy2MouseClicked
        // TODO add your handling code here:
                pomocniczy2.removeAllItems();
        for(Sedzia s : sedziowie){
            pomocniczy2.addItem(s.imie+" "+s.nazwisko);
        }        
    }//GEN-LAST:event_pomocniczy2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StartFrame.currentState = new StartFrame();
        StartFrame.currentState.setVisible(true);
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void goscie2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goscie2MouseClicked
        // TODO add your handling code here:
                goscie2.removeAllItems();
        for(Druzyna ac : druzyny){
            goscie2.addItem(ac.nazwa);
        }
    }//GEN-LAST:event_goscie2MouseClicked

    private void goscie2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goscie2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_goscie2ActionPerformed

    private void gospodarze2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gospodarze2MouseClicked
        // TODO add your handling code here:
        gospodarze2.removeAllItems();
        for(Druzyna d : druzyny){
            gospodarze2.addItem(d.nazwa);
        }
    }//GEN-LAST:event_gospodarze2MouseClicked

    private void gospodarze2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gospodarze2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gospodarze2ActionPerformed

    private void stworzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stworzActionPerformed
        // TODO add your handling code here:
        Mecz nowy = new Mecz();
        nowy.dyscyplina = (String) wybor.getSelectedItem();
        nowy.glowny = (Sedzia) sedzia.getSelectedItem();
        nowy.goscie = (Druzyna) goscie2.getSelectedItem();
        nowy.gospodarze = (Druzyna) gospodarze2.getSelectedItem();
        nowy.pkt_gosci = Float.parseFloat(w_goscie.getText()); ;
        nowy.pkt_gosp = Float.parseFloat(w_gospodarze.getText()); 
        if(nowy.pkt_gosp > nowy.pkt_gosci){
            nowy.gospodarze.punkty +=2;
        }
        else if(nowy.pkt_gosp < nowy.pkt_gosci){
            nowy.goscie.punkty +=2;
        }
        else if(nowy.pkt_gosp == nowy.pkt_gosci){
            nowy.goscie.punkty +=1;
            nowy.gospodarze.punkty +=1;
        }
        if(x == 1){
            nowy.pomocniczy_1 = (Sedzia) pomocniczy1.getSelectedItem();
            nowy.pomocniczy_2 = (Sedzia) pomocniczy2.getSelectedItem(); 
            mecze_siatkowka.add(nowy);
        }
        if(x == 2){
            mecze_ognie.add(nowy);
        }
        if(x == 3){
            mecze_lina.add(nowy);
        }
    }//GEN-LAST:event_stworzActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeczFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeczFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeczFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeczFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeczFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> goscie2;
    private javax.swing.JComboBox<String> gospodarze2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> pomocniczy1;
    private javax.swing.JComboBox<String> pomocniczy2;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s3;
    private javax.swing.JComboBox<String> sedzia;
    private javax.swing.JButton stworz;
    private javax.swing.JTextField w_goscie;
    private javax.swing.JTextField w_gospodarze;
    private javax.swing.JComboBox<String> wybor;
    // End of variables declaration//GEN-END:variables
}
